import nodemailer from 'nodemailer';
import emailTemplates from 'email-templates';
import {server, smtp} from './config';
import tracer from "./tracer";
import {sprintf} from 'sprintf-js';

const email = new emailTemplates({
  message: {
    from: {
      address: smtp.user,
      name: server.name,
    },
  },
  transport: {
    jsonTransport: true,
  }
});

export default {
  sendContactUsMail: (params) => {
    return new Promise((resolve, reject) => {
      email.render('../email-templates/contact-us/html.pug', params)
        .then(html => {
          let transporter = nodemailer.createTransport({
            // service: smtp.service,
            host: smtp.host,
            port: smtp.port,
            secure: smtp.secure,
            auth: {
              user: smtp.user, //generated by Mailtrap
              pass: smtp.pass //generated by Mailtrap
            },
            tls: {
              rejectUnauthorized: false,
            }
          });

          const mailOptions = {
            from: sprintf("%s <%s>", 'PM', smtp.user),
            to: smtp.user,
            subject: 'اتصل بن(Contact Us)',
            html,
          };

          tracer.info(mailOptions);

          transporter.sendMail(mailOptions, function(error, info){
            if (error) {
              reject(error);
            } else {
              resolve(info);
            }
          });
        })
        .catch(reject);
    });
  },
  sendMassMail: (to, name, subject, message) => {
    return new Promise((resolve, reject) => {
      // email.render('../email_templates/email_verify/html.pug', {
      //   name: name,
      //   subject,
      //   message,
      // })
      //   .then((html) => {
          let transporter = nodemailer.createTransport({
            // service: smtp.service,
            host: smtp.host,
            port: smtp.port,
            secure: smtp.secure,
            auth: {
              user: smtp.user, //generated by Mailtrap
              pass: smtp.pass //generated by Mailtrap
            },
            tls: {
              rejectUnauthorized: false,
            }
          });

          const mailOptions = {
            from: sprintf("%s <%s>", name, smtp.user),
            to: to,
            subject: subject,
            text: message,
          };

          tracer.info('mailOptions', mailOptions);

          transporter.sendMail(mailOptions, function(error, info){
            if (error) {
              reject(error);
            } else {
              resolve(info);
            }
          });
    //     })
    //     .catch(reject);
    });
  },
  sendCourseJoinMail: (to, name, subject) => {
    return new Promise((resolve, reject) => {
      email.render('../email_templates/email_verify/html.pug', {
        name: name,
        subject,
        message,
      })
        .then((html) => {
          let transporter = nodemailer.createTransport({
            // service: smtp.service,
            host: smtp.host,
            port: smtp.port,
            secure: smtp.secure,
            auth: {
              user: smtp.user, //generated by Mailtrap
              pass: smtp.pass //generated by Mailtrap
            },
            tls: {
              rejectUnauthorized: false,
            }
          });

          const mailOptions = {
            from: sprintf("%s <%s>", name, smtp.user),
            to: to,
            subject: subject,
            html: html,
          };

          tracer.info('mailOptions', mailOptions);

          transporter.sendMail(mailOptions, function(error, info){
            if (error) {
              reject(error);
            } else {
              resolve(info);
            }
          });
        })
        .catch(reject);
    });
  }
};
